---
sidebar: sidebar 
permalink: concept_lic_production.html 
keywords: license, licensing, production, purchased, standard, premium, premium xl 
summary: Depois de determinar que o ONTAP Select é adequado para sua organização, você pode comprar as licenças necessárias para dar suporte a uma implantação de produção. Você deve escolher as categorias de capacidade ou o modelo de licenciamento de pools de capacidade, bem como a capacidade de storage para cada implantação. 
---
= Saiba mais sobre as licenças ONTAP Select adquiridas para implantações em produção
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Após determinar que ONTAP Select é adequado para sua organização, você pode adquirir as licenças necessárias para dar suporte a uma implementação em produção. Você deve escolher o modelo de licenciamento Capacity Pools ou Capacity Tiers, bem como a capacidade de storage para cada implementação.



== Caraterísticas comuns de licenciamento

Os modelos de licenciamento _Capacity Pools_ e _Capacity Tiers_ são muito diferentes em vários aspectos. No entanto, os dois modelos de licenciamento compartilham várias características em comum, incluindo:

* Você precisa adquirir uma ou mais licenças conforme necessário ao implantar o ONTAP Select em um ambiente de produção.
* A capacidade de armazenamento de uma licença é alocada em incrementos de 1 TB.
* Todas as ofertas de modelo de licenciamento da plataforma são suportadas (standard, premium e premium XL).
* Entre em Contato com a equipe ou parceiro da sua conta NetApp para obter assistência conforme necessário ao adquirir as licenças necessárias.
* Você deve carregar os arquivos de licença para o utilitário de administração implantar, que então aplica as licenças com base no modelo de licenciamento.
* Depois de instalar e aplicar uma licença, você pode adicionar capacidade adicional entrando em Contato com sua equipe ou parceiro de conta do NetApp para obter uma licença atualizada.
* Um nó ONTAP Select que é implantado inicialmente com uma licença adquirida não pode ser convertido em uma licença de avaliação.




== Modelo de licenciamento de categorias de capacidade

Há várias características exclusivas do modelo de licenciamento de camadas de capacidade, incluindo:

* Você precisa adquirir uma licença para cada nó do ONTAP Select.
* O valor mínimo que você pode comprar é de 1 TB.
* Cada licença do nível de capacidade tem uma capacidade de storage e é bloqueada para um nó específico.
* A capacidade de storage identifica a capacidade bruta e corresponde ao tamanho total permitido dos discos de dados disponíveis para a máquina virtual ONTAP Select.
* NetApp gera um número de série de licença de nove dígitos para cada nó ONTAP Select.
* O storage alocado a um nó é perpétuo (não requer renovação), mas você deve renovar o contrato de suporte associado à licença.
* Cada nó ONTAP Select em um par de HA requer uma licença que seja pelo menos tão grande quanto o storage bruto conectado ao nó.
* O número de série do nó é de nove dígitos e igual ao número de série da licença.
* Você pode aplicar o arquivo de licença durante a implantação do cluster ou dentro de 30 dias após a criação de um cluster.




== Modelo de licenciamento de pools de capacidade

Existem várias caraterísticas exclusivas do modelo de licenciamento de pools de capacidade, incluindo:

* Você precisa comprar uma licença para cada pool de capacidade compartilhada.
* O valor mínimo que você pode comprar é de 2 TB.
* Cada licença do Capacity Pool possui uma capacidade de storage e está vinculada a uma instância específica do License Manager dentro de um utilitário de administração Deploy.
* A capacidade de storage identifica a capacidade bruta e corresponde ao tamanho total permitido dos agregados de dados que você pode criar na máquina virtual ONTAP Select.
* Um número de série de licença de nove dígitos é gerado pelo NetApp para cada pool de capacidade.
* O storage alocado a um pool de capacidade é válido apenas por um tempo específico com base na compra (renovação necessária).
* O License Manager gera um número de série de nó de vinte dígitos com base no número de série da licença do Capacity Pool.
* Todos os nós do ONTAP Select em um cluster compartilham a mesma capacidade de licença. Isso significa que a licença deve ser grande o suficiente para fornecer o storage alocado a todos os nós do cluster.
* Cada nó aluga automaticamente a capacidade de storage para agregados de dados locais a partir de um pool de capacidade compartilhado.


.O que vem a seguir?
* link:concept_lic_platforms.html["Saiba mais sobre as ofertas de licença da plataforma para o ONTAP Select"]
* link:concept_lic_cp_operation.html["Saiba mais sobre o modelo de licenciamento ONTAP Select Capacity Pools"]

