---
sidebar: sidebar 
permalink: concept_lic_evaluation.html 
keywords: license, licensing, evaluation, upgrade license 
summary: Você pode usar uma licença de avaliação se quiser avaliar o ONTAP Select antes de tomar a decisão de comprar. A licença de avaliação está incluída no utilitário de administração ONTAP Select Deploy e é aplicada automaticamente a cada nó do ONTAP Select como parte de uma implantação de avaliação. 
---
= Licenças de avaliação para implantações ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode implantar o ONTAP Select com uma licença de avaliação ou uma licença adquirida. A licença escolhida deve ser aplicada a cada um dos nós no cluster do ONTAP Select e, portanto, a todo o cluster. Você pode usar uma licença de avaliação se quiser avaliar o ONTAP Select antes de tomar a decisão de comprar. A licença de avaliação está incluída no utilitário de administração ONTAP Select Deploy e é aplicada automaticamente a cada nó do ONTAP Select como parte de uma implantação de avaliação.

[NOTE]
====
Para baixar o utilitário de administração ONTAP Select Deploy, você precisa do seguinte:

* Uma conta do site de suporte da NetApp registrada. Se você não tiver uma conta, https://mysupport.netapp.com/site/user/registration["Registo do utilizador"^] consulte .
* Para https://mysupport.netapp.com/site/downloads/evaluation/ontap-select["Aceite o contrato de licença do utilizador final"^] uma implantação do ONTAP Select com uma licença de avaliação.


====
Há várias considerações ao implantar e dar suporte a um cluster de avaliação:

* Você só pode usar o cluster para fins de avaliação. Não é necessário usar um cluster com uma licença de avaliação em um ambiente de produção.
* Você deve usar o utilitário de administração ONTAP Select Deploy da seguinte forma ao configurar cada host:
+
** Não forneça um número de série
** Configure para usar uma licença de avaliação






== Caraterísticas de licenciamento

A licença de avaliação ONTAP Select tem as seguintes caraterísticas:

* Não é necessária uma licença de produção com capacidade de armazenamento
* O número de série do nó é de vinte dígitos e gerado automaticamente pelo ONTAP Select Deploy
+
(Você não o adquire diretamente de NetApp)

* O período de avaliação fornecido pela licença pode ser de até 90 dias
* O storage máximo alocado por cada nó é o mesmo que uma licença de produção




== Atualize para uma licença de produção

Você pode atualizar um cluster de avaliação do ONTAP Select para usar uma licença de produção. Você deve estar ciente das seguintes restrições:

* Você deve usar o utilitário de administração implantar para executar a atualização da licença
* Uma licença de camada de capacidade pode ser usada, no entanto, o licenciamento de pools de capacidade não é suportado
* Cada nó precisa ter storage suficiente alocado para dar suporte ao mínimo necessário para uma licença de produção, com base no tamanho do cluster


Consulte link:task_adm_licenses.html["Converter uma licença de avaliação em uma licença de produção"] para obter mais informações.

.Informações relacionadas
link:deploy-evaluation-ontap-select-ovf-template.html["Implantar uma instância de avaliação de 90 dias de um cluster do ONTAP Select"]
