---
sidebar: sidebar 
permalink: concept_lic_platforms.html 
keywords: license, licensing, platform license offerings, license offerings, standard, premium, premium xl 
summary: Você pode adquirir uma licença de camada de capacidade ou pool de capacidade do ONTAP Select em um dos três níveis de capacidade da plataforma. Essas ofertas de licença determinam os recursos dos hosts nos quais você implanta o ONTAP Select. 
---
= Saiba mais sobre as ofertas de licença da plataforma para o ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode comprar uma licença do nível de capacidade ou do pool de capacidade do ONTAP Select nos níveis XL padrão, premium ou premium. Essas ofertas de licença determinam os recursos dos hosts nos quais você implanta o ONTAP Select.



== O que uma oferta de licença de plataforma oferece

Uma oferta de licença específica determina os recursos do host do hipervisor em duas áreas:

* Tipo de instância (CPU, memória)
* Recursos adicionais


As ofertas de licença são organizadas em uma ordem crescente de capacidades, desde o padrão ao premium XL. Em geral, a opção de licença que você escolher concede a você os recursos desse nível e todos os níveis mais baixos. Por exemplo, o nível premium fornece as capacidades de premium e padrão.

A tabela a seguir compara os recursos das ofertas de licença padrão, premium e premium XL.

[cols="25,25,25,25,25"]
|===
2+| A licença suporta ... | Padrão | Premium | XL premium 


2+| Tipo de instância | Somente pequeno | Pequeno ou médio | Pequeno, médio ou grande 


.2+| Unidades de disco rígido (HDD) em um ... | Configuração RAID de hardware | Sim | Sim | Sim 


| configuração vNAS | Sim | Sim | Sim 


.3+| Unidades de estado sólido (SSD) em um ... | Configuração RAID de hardware | Não | Sim | Sim 


| Configuração RAID de software | Não | Sim | Sim 


| configuração vNAS | Sim | Sim | Sim 


.3+| Unidades NVMe em um ... | Configuração RAID de hardware | Não | Não | Sim 


| Configuração RAID de software | Não | Não | Sim 


| configuração vNAS | Sim | Sim | Sim 


2+| SDS do MetroCluster | Não | Sim | Sim 
|===

NOTE: Máquinas virtuais baseadas em kernel (KVM) não suportam o tipo de instância grande.



== Compare o suporte de hardware para ofertas de licença de plataforma

As ofertas de licença XL padrão, premium e premium suportam uma ampla gama de hardware e software. Para obter informações atualizadas sobre versões de hardware e software, consulte o link:https://mysupport.netapp.com/matrix/["Ferramenta de Matriz de interoperabilidade"^].

[role="tabbed-block"]
====
.Item principal
--
[cols="5"30"]
|===


2+| Tipo de item principal 3+| Descrição 


2+| Protocolos de host 3+| NFS, SMB/CIFS, iSCSI e NVMe sobre TCP 


2+| Opções de implantação 3+| Nó único; Cluster de dois nós (par HA); Cluster de quatro, seis, oito, dez ou doze nós 


2+| Capacidade suportada (por nó) 3+| Até 400TB dados brutos (ESXi e KVM) 
|===
--
.Hardware
--
[cols="5"30"]
|===


2+| Tipo de hardware 3+| Descrição 


2+| Tamanho da instância | Pequeno | Média | Grande 


2+| Família CPU | Intel Xeon E5-26xx v3 (Haswell) ou posterior | Intel Xeon E5-26xx v3 (Haswell) ou posterior | Intel Xeon E5-26xx v3 (Haswell) ou posterior 


2+| ONTAP Select CPU / memória | 4 CPUs virtuais (vCPUs) / 16GB GB de RAM | 8 vCPUs / 64GB GB de RAM | 16 vCPUs / 128GB GB de RAM 


2+| Requisitos mínimos de CPU/memória do host 1 | 6 núcleos / 24GB GB de RAM | 10 núcleos / 72GB GB de RAM | 18 núcleos / 136GB GB de RAM 


2+| Rede (por nó) 3+| No mínimo, duas portas 1GbE para um cluster de nó único. No mínimo, quatro portas 1GbE para um cluster de dois nós (par HA). No mínimo, duas portas 10GbE para um cluster de quatro, seis, oito, dez ou doze nós. 
|===
^1^ Assume dois núcleos e 8 GB de RAM para o hipervisor.

--
.Tipo de armazenamento
--
A tabela a seguir fornece o tipo de licença mínimo necessário para o armazenamento especificado. 

[cols="5"30"]
|===


2+| Tipo de armazenamento 3+| Descrição 


2+| Tipo de licença | Padrão | Premium | XL premium 


2+| Tamanho da instância | Pequeno | Pequeno e médio | Pequeno, médio e grande 


2+| DAS local com controladora RAID de hardware | 8 - 60 unidades | 8 - 60 unidades | 8 - 60 unidades 


2+| HDD (SAS, NL-SAS, SATA) | Não aplicável | 4 – 60 unidades | 4 – 60 unidades 


2+| SSD (SAS) | Não aplicável | 4 – 60 unidades (somente SSD) | 4 – 60 unidades (somente SSD) 


2+| DAS local com software RAID | Não aplicável | Aplicável | 4 - 14 unidades (somente NVMe) 


2+| 1.3 3+| Armazenamentos de dados hospedados em arrays externos são conectados por meio de FC, FCoE, iSCSI e NFS (o NFS não é compatível com KVM). Esses datastores fornecem alta disponibilidade e resiliência. 
|===
1 o suporte ao protocolo de matriz externa reflete a conetividade de storage em rede.

--
.Software
--
[cols="5"30"]
|===


2+| Tipo de software 3+| Descrição 


2+| Suporte a hipervisor (VMware) 3+| VMware vSphere 9.0, VMware vSphere 8.0GA e atualizações 1 a 3, VMware vSphere 7.0GA e atualizações 1 a 3C 


2+| Suporte a hipervisor (KVM)  a| 
Red Hat Enterprise Linux 64-bit (KVM) 10.1, 10.0, 9.7, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.8, 8.7 e 8.6

Rocky Linux (KVM) 10.0, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.9, 8.8, 8.7 e 8.6

*Nota*: Existem limitações no fluxo de trabalho RAID por software para hipervisores KVM em hosts RHEL 10.1 e 10.0 e Rocky Linux 10.0. Para obter mais informações, consulte os seguintes artigos da Knowledge Base:

* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4020["CDEPLOY-4020: ONTAP Select Deploy: Mensagem de aviso ao criar o Cluster HWR usando RHEL 10 e ROCKY 10"^]
* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4025["CDEPLOY-4025: ONTAP Select DeployGUI: Pools de armazenamento e discos de armazenamento não visíveis para SWR na página de criação de cluster em hosts com RHEL10/Rocky 10"^]




2+| Software de gerenciamento 3+| Pacote de gerenciamento NetApp Active IQ Unified Manager ONTAP Select Deploy Utility SnapCenter (opcional) 
|===
--
====
.Informações relacionadas
* link:concept_lic_production.html["Saiba mais sobre os tipos de licença de nível de capacidade e pool de capacidade"]

