---
sidebar: sidebar 
permalink: concept_lic_cp_serial_number.html 
keywords: license, licensing, Capacity Pools, node serial numbers 
summary: Com o modelo de licenciamento de categorias de capacidade, o número de série do nó de nove dígitos é o mesmo que o número de série da licença atribuído ao nó. No entanto, os números de série atribuídos aos nós que usam o modelo de licenciamento de pools de capacidade têm um formato diferente. 
---
= Números de série do nó para o modelo de licenciamento de pools de capacidade do ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Com o modelo de licenciamento de categorias de capacidade, o número de série do nó de nove dígitos é o mesmo que o número de série da licença atribuído ao nó. No entanto, os números de série atribuídos aos nós que usam o modelo de licenciamento de pools de capacidade têm um formato diferente.

O número de série de um nó que usa o licenciamento de pools de capacidade tem o seguinte formato:

`999 ppppppppp nnnnnnnn`


NOTE: Os espaços foram adicionados para maior clareza, mas não fazem parte do número de série real.

A tabela a seguir descreve cada seção do número de série do nó da esquerda para a direita.

[cols="15,85"]
|===
| Secção | Descrição 


| '999' | Valor constante de três dígitos reservado pela NetApp. 


| pppppppppppp | Número de série de licença variável de nove dígitos atribuído ao pool de capacidade pela NetApp 


| nnnnnnnn | Valor variável de oito dígitos gerado pelo Gerenciador de licenças para cada nó usando o pool de capacidade 
|===

CAUTION: Ao abrir um chamado com o suporte da NetApp envolvendo um nó que utiliza uma licença do Capacity Pool, você deve fornecer o número de série da licença do Capacity Pool, que possui nove dígitos. Você não pode fornecer o número de série completo do nó, que possui vinte dígitos. Você pode obter o número de série da licença a partir do número de série do nó, ignorando os três primeiros dígitos do número de série do nó ('999') e extraindo os nove dígitos seguintes (ppppppppp).
