---
sidebar: sidebar 
permalink: concept_lic_platforms.html 
keywords: license, licensing, platform license offerings, license offerings, standard, premium, premium xl 
summary: Você pode adquirir uma licença de camada de capacidade ou pool de capacidade do ONTAP Select em um dos três níveis de capacidade da plataforma. Essas ofertas de licença determinam os recursos dos hosts nos quais você implanta o ONTAP Select. 
---
= Saiba mais sobre as ofertas de licença da plataforma para o ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode comprar uma licença do nível de capacidade ou do pool de capacidade do ONTAP Select nos níveis XL padrão, premium ou premium. Essas ofertas de licença determinam os recursos dos hosts nos quais você implanta o ONTAP Select.



== O que uma oferta de licença de plataforma oferece

Uma oferta de licença específica define e restringe os recursos do host do hipervisor em duas áreas:

* Tipo de instância (CPU, memória)
* Recursos adicionais


As ofertas de licença são organizadas em uma ordem crescente de capacidades, desde o padrão ao premium XL. Em geral, a opção de licença que você escolher concede a você os recursos desse nível e todos os níveis mais baixos. Por exemplo, o nível premium fornece as capacidades de premium e padrão.



== Ofertas de licença de plataforma

Há três ofertas de licença de plataforma disponíveis.



=== Padrão

A oferta padrão oferece os seguintes recursos:

* Apenas tipo de instância pequena
* Apenas unidades de disco rígido (HDD)
* Apenas controlador RAID de hardware local
* VNAS




=== Premium

A oferta premium oferece os seguintes recursos:

* Tipo de instância pequena ou média
* Unidades de disco rígido (HDD) ou unidades de estado sólido (SSD)
* Controlador RAID de hardware local ou RAID de software
* VNAS
* SDS do MetroCluster




=== XL premium

A oferta Premium XL oferece os seguintes recursos:

* Tipo de instância pequena, média ou grande
* HDDs, SSDs ou unidades NVMe
* Controlador RAID de hardware local ou RAID de software
* VNAS
* SDS do MetroCluster



NOTE: O uso do tipo de instância grande em uma configuração RAID de software não é suportado em uma Máquina Virtual Baseada em Kernel (KVM).



== Compare o suporte de hardware para ofertas de licença de plataforma

As ofertas de licença XL padrão, premium e premium suportam uma ampla gama de hardware e software. Para obter informações atualizadas sobre versões de hardware e software, consulte o link:https://mysupport.netapp.com/matrix/["Ferramenta de Matriz de interoperabilidade"^].

[role="tabbed-block"]
====
.Item principal
--
[cols="5"30"]
|===


2+| Tipo de item principal 3+| Descrição 


2+| Protocolos de host 3+| NFS, SMB/CIFS, iSCSI e NVMe sobre TCP 


2+| Opções de implantação 3+| Cluster de nó único de dois nós (par de HA) cluster de quatro, seis ou oito nós 


2+| Capacidade suportada (por nó) 3+| Até 400TB dados brutos (ESXi e KVM) 
|===
--
.Hardware
--
[cols="5"30"]
|===


2+| Tipo de hardware 3+| Descrição 


2+| Tamanho da instância | Pequeno | Média | Grande 


2+| Família CPU | Intel Xeon E5-26xx v3 (Haswell) ou posterior | Intel Xeon E5-26xx v3 (Haswell) ou posterior | Intel Xeon E5-26xx v3 (Haswell) ou posterior 


2+| ONTAP Select CPU / memória | 4 CPUs virtuais (vCPUs) / 16GB GB de RAM | 8 vCPUs / 64GB GB de RAM | 16 vCPUs / 128GB GB de RAM 


2+| Requisitos mínimos de CPU/memória do host 1 | 6 núcleos / 24GB GB de RAM | 10 núcleos / 72GB GB de RAM | 18 núcleos / 136GB GB de RAM 


2+| Rede (por nó) 3+| Mínimo de duas portas de 1GbE GbE para um cluster de nó único, mínimo de quatro portas de 1GbE GbE para um cluster de dois nós (par de HA), no mínimo, de duas portas de 10GbE GbE para um cluster de quatro, seis ou oito nós 
|===
O 1 assume dois núcleos e 8GB GB de RAM para o hypervisor.

--
.Tipo de armazenamento
--
A tabela a seguir fornece o tipo de licença mínimo necessário para o armazenamento especificado. 

[cols="5"30"]
|===


2+| Tipo de armazenamento 3+| Descrição 


2+| Tipo de licença | Padrão | Premium | Pemium XL 


2+| Tamanho da instância | Pequeno | Pequeno e médio | Pequeno, médio e grande 


2+| DAS local com controladora RAID de hardware | 8 - 60 unidades | 8 - 60 unidades | 8 - 60 unidades 


2+| HDD (SAS, NL-SAS, SATA) | Não aplicável | 4 – 60 unidades | 4 – 60 unidades 


2+| SSD (SAS) | Não aplicável | 4 – 60 unidades (somente SSD) | 4 – 60 unidades (somente SSD) 


2+| DAS local com software RAID | Não aplicável | Não aplicável | 4 - 14 unidades (somente NVMe) 


2+| 1.3 3+| Armazenamentos de dados hospedados em arrays externos são conectados por meio de FC, FCoE, iSCSI e NFS (o NFS não é compatível com KVM). Esses datastores fornecem alta disponibilidade e resiliência. 
|===
1 o suporte ao protocolo de matriz externa reflete a conetividade de storage em rede.

--
.Software
--
[cols="5"30"]
|===


2+| Tipo de software 3+| Descrição 


2+| Suporte a hipervisor (VMware) 3+| VMware vSphere 8.0GA e atualizações de 1 a 3 VMware vSphere 7.0GA e atualizações de 1 a 3C 


2+| Suporte a hipervisor (KVM) 3+| Red Hat Enterprise Linux 64 bits (KVM) 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.8, 8.7 e 8.6 Rocky Linux (KVM) 9.6 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.9, 8.8, 8.7 e 8.6 


2+| Software de gerenciamento 3+| Pacote de gerenciamento NetApp Active IQ Unified Manager ONTAP Select Deploy Utility SnapCenter (opcional) 
|===
--
====
.Informações relacionadas
link:concept_lic_production.html["Saiba mais sobre os tipos de licença de nível de capacidade e pool de capacidade"].
