---
sidebar: sidebar 
permalink: concept_adm_upgrading_nodes.html 
keywords: administer, administering, web, upgrading nodes 
summary: Depois de implantar um cluster ONTAP Select, você pode atualizar a imagem ONTAP de cada nó conforme necessário usando o procedimento de atualização padrão do software ONTAP. 
---
= Atualizar os nós de ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Depois de implantar um cluster do ONTAP Select, você pode atualizar a imagem do ONTAP em cada nó do cluster conforme necessário.


CAUTION: Você não pode usar o utilitário de administração implantar para executar atualizações de nós ONTAP Select existentes. O utilitário implantar só pode ser usado para criar novos clusters do ONTAP Select.



== Procedimento geral

Em um alto nível, você deve usar as etapas a seguir para atualizar um nó ONTAP Select existente.

.Passos
. Acesse a link:https://mysupport.netapp.com/site/downloads/["Downloads do site de suporte da NetApp"^] página.
. Deslize para baixo e selecione *ONTAP Select Image*.
. Selecione a versão desejada da imagem de instalação.
. Reveja o Contrato de Licença de Utilizador final (EULA) e selecione *Accept & continue* (aceitar e continuar).
. Selecione e faça o download do pacote *ONTAP Select Image Upgrade* apropriado. Responda a todas as solicitações conforme necessário.
+
Consulte a link:reference_release_notes.html["notas de lançamento"] para obter informações adicionais e quaisquer procedimentos necessários antes de atualizar um nó ONTAP Select.

. Atualize o nó ONTAP Select usando os procedimentos de atualização padrão do ONTAP com o arquivo de atualização do ONTAP Select. Para obter informações sobre caminhos de atualização suportados, consulte o link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html["Caminhos de atualização do ONTAP compatíveis"^].




== Reverter um nó ONTAP Select

Não é possível reverter um nó ONTAP Select para uma versão anterior à na qual ele foi originalmente instalado. Por exemplo:

O ONTAP Select 9.16.1 é instalado inicialmente.:: Você pode atualizar o nó para a versão 9.17.1 e, em seguida, reverter para a versão 9.16.1, se necessário.
O ONTAP Select 9.17.1 é instalado inicialmente.:: Não é possível reverter a versão, pois não havia nenhuma versão anterior instalada.




== Use o driver de rede VMXNET3

VMXNet3 é o driver de rede padrão incluído com novas implantações de cluster no VMware ESXi. Se você atualizar um nó ONTAP Select existente executando o ONTAP Select 9,4 ou anterior, o driver de rede não será atualizado automaticamente. Você deve atualizar manualmente para VMXNET3. Você deve entrar em Contato com o suporte da NetApp para obter assistência com a atualização.

.Informações relacionadas
link:https://docs.netapp.com/us-en/ontap/upgrade/index.html["Visão geral da atualização do ONTAP"^]
