---
sidebar: sidebar 
permalink: reference_lic_ontap_features.html 
keywords: license, licensing, ontap features, default ontap features 
summary: O ONTAP Select oferece suporte completo para a maioria das funcionalidades do ONTAP. Muitos dos recursos do ONTAP são licenciados automaticamente para cada nó ao implantar um cluster. No entanto, alguns recursos exigem uma licença separada. 
---
= Suporte do ONTAP Select para recursos do ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O ONTAP Select oferece suporte completo para a maioria das funcionalidades do ONTAP. Muitos dos recursos do ONTAP são licenciados automaticamente para cada nó ao implantar um cluster. No entanto, alguns recursos exigem uma licença separada.


NOTE: Os recursos do ONTAP que têm dependências específicas de hardware geralmente não são suportados com o ONTAP Select.



== Os recursos do ONTAP são ativados automaticamente por padrão

Os seguintes recursos do ONTAP são compatíveis com o ONTAP Select e licenciados por padrão:

* Proteção autônoma contra ransomware (ARP) (atualizações manuais)
* CIFS
* Deduplicação e compactação
* FlexCache
* FlexClone
* ISCSI
* NDMP
* Encriptação de volume NetApp (apenas países não restritos)
* NFS
* NVMe sobre TCP
* Funcionalidade de alocação a vários clientes da ONTAP
* ONTAP S3
* S3 SnapMirror
* SnapMirror
* Nuvem SnapMirror
* SnapRestore
* SnapVault
* Recuperação de desastres de VM de storage (SVM DR)
+

NOTE: O ONTAP Select é compatível com o SVM DR como origem e destino, no máximo 16 relacionamentos. A compatibilidade com SVM DR está limitada ao uso da versão de origem do ONTAP nas versões mais de 2. Por exemplo, a fonte ONTAP Select 9.12.1 pode se conetar ao ONTAP de destino versões 9.12.1, 9.13.1 ou 9.14.1.





== Recursos do ONTAP licenciados separadamente

Você deve adquirir uma licença separada para qualquer recurso do ONTAP que não esteja habilitado por padrão, incluindo:

* FabricPool
* MetroCluster SDS (oferta de licença premium ONTAP Select)
* SnapLock Enterprise para ONTAP Select 9.16.1 e anteriores (disponível emlink:https://mysupport.netapp.com/site/["Site de suporte da NetApp"^] )
+

NOTE: A SnapLock Compliance não é suportada pelo ONTAP Select.

+
** Cópias Snapshot à prova de violações


* SnapLock Select



NOTE: Você não precisa de uma licença FabricPool ao utilizar o StorageGRID.

.Informações relacionadas
* link:concept_ots_overview.html#comparing-ontap-select-and-ontap-9["Comparando ONTAP Select e ONTAP 9"]
* link:https://mysupport.netapp.com/site/systems/master-license-keys["Chaves de licença principal do NetApp ONTAP"^]

