---
sidebar: sidebar 
permalink: reference_plan_ots_vcenter.html 
keywords: plan, planning, vmware vcenter, vcenter server, vcenter 
summary: Há vários requisitos de Planejamento relacionados ao VMware vCenter que você deve considerar. 
---
= Servidor ONTAP Select VMware vCenter no ESXi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você deve definir uma conta do vCenter Server e associá-la a uma função que contenha o Privileges administrativo necessário.


NOTE: Você também precisa do nome de domínio ou endereço IP totalmente qualificado do servidor vCenter que gerencia os hosts do hypervisor ESXi onde o ONTAP Select é implantado.



[[administrative-privileges]]
== Privileges administrativo

Os Privileges administrativos mínimos necessários para criar e gerenciar um cluster do ONTAP Select são apresentados abaixo.



[[datastore]]
=== Armazenamento de dados

* Alocar espaço
* Navegue pelo datastore
* Operações de arquivo de baixo nível
* Atualize os arquivos da máquina virtual
* Atualize os metadados da máquina virtual




[[host]]
=== Host

Configuração::
+
--
* Configuração de rede
* Gerenciamento do sistema


--
Operações locais::
+
--
* Criar máquina virtual
* Eliminar a máquina virtual
* Reconfigure a máquina virtual


--




[[network]]
=== Rede

* Atribuir rede




[[virtual-machine]]
=== Máquina virtual

Configuração:: Todos Privileges na categoria.
Interação:: Todos Privileges na categoria.
Inventário:: Todos Privileges na categoria.
Provisionamento:: Todos Privileges na categoria.




[[vapp]]
=== VApp

Todos Privileges na categoria.

.Informações relacionadas
link:reference_plan_dep_vmware.html#vmware-vcenter-server-considerations["Saiba mais sobre os privilégios do VMware vSphere para vSAN ESA no vCenter"]
