---
sidebar: sidebar 
permalink: reference_plan_ots_hardware.html 
keywords: plan, planning, vmware, hardware, hardware requirements 
summary: Há vários requisitos de hardware e problemas de Planejamento que você deve considerar relacionados ao ambiente VMware. 
---
= Considerações sobre hardware e hypervisor VMware do ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Há vários requisitos de hardware e problemas de Planejamento que você deve considerar relacionados ao ambiente VMware.



== Requisitos de hipervisor

Existem vários requisitos relacionados ao hypervisor em que o ONTAP Select é executado.


NOTE: Você deve revisar olink:reference_release_notes.html["Notas de versão do ONTAP Select"] para quaisquer outras restrições ou limitações conhecidas.



=== Licenciamento da VMware

Para implantar um cluster do ONTAP Select, sua organização deve ter uma licença válida do VMware vSphere para os hosts de hypervisor em que o ONTAP Select é executado. Você deve usar as licenças apropriadas para sua implantação.



=== Compatibilidade de software

Você pode implantar o ONTAP Select em hipervisores KVM e ESXi.

[role="tabbed-block"]
====
.KVM
--
O ONTAP Select oferece suporte às seguintes versões do hipervisor KVM:

* KVM no Red Hat Enterprise Linux (RHEL) 10.1, 10.0, 9.7, 9.6, 9.5, 9.4, 9.2, 9.1, 9.0, 8.8, 8.7, e 8.6
* KVM no Rocky Linux 10.1, 10.0, 9.7, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.9, 8.8, 8.7 e 8.6


--
.ESXi
--
O ONTAP Select oferece suporte às seguintes versões do hipervisor ESXi:

* VMware ESXi 9.0
* VMware ESXi 8,0 U3
* VMware ESXi 8,0 U2
* VMware ESXi 8,0 U1 (compilação 21495797)
* VMware ESXi 8,0 GA (compilação 20513097)



NOTE: O NetApp oferece suporte ao ONTAP Select nas versões identificadas do ESXi, desde que o VMware continue a suportar as mesmas versões.


NOTE: O ESXi 7.0 GA atingiu o fim da sua disponibilidade.  Se você possui clusters ONTAP Select com esta versão, é necessário atualizar para as versões compatíveis, conforme indicado em [inserir aqui o caminho aqui]. https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade (IMT)"^] .

--
====


=== VMware vCenter e hosts ESXi independentes

Se um host de hipervisor ESXi for gerenciado por um servidor vCenter, você deverá Registrar o host no utilitário de administração implantar usando as credenciais do vCenter. Não é possível Registrar o host como um host autônomo usando as credenciais ESXi.



== Requisitos básicos de hardware

O host do hypervisor físico onde você implantar o ONTAP Select deve atender a vários requisitos de hardware. Você pode escolher qualquer plataforma para o host do hypervisor, desde que atenda aos requisitos mínimos de hardware. Os seguintes fornecedores fornecem plataformas de hardware suportadas: Cisco, Dell, HP, Fujitsu, Lenovo e Supermicro.


NOTE: A partir da versão 9.9.1 do ONTAP Select , somente os modelos de CPU baseados em Intel Xeon Sandy Bridge ou posteriores são suportados.

Consulte a https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade, janela em branco"] para obter mais informações.



=== Requisitos básicos de hardware

Existem vários requisitos comuns de hardware que se aplicam a todas as plataformas, independentemente do tipo de instância do nó ou da oferta de licença.

.Processador
Os microprocessadores suportados incluem processadores Intel Xeon para servidor, consulte link:https://www.intel.com/content/www/us/en/products/processors/xeon/view-all.html?Processor+Type=1003["Processadores Intel Xeon, janela em branco"] para maiores informações.


NOTE: Os processadores Advanced Micro Devices (AMD) não são compatíveis com o ONTAP Select.

.Configuração Ethernet
Existem várias configurações Ethernet suportadas com base no tamanho do cluster.

[cols="2,3,3"]
|===
| Tamanho do cluster | Requisitos mínimos | Requisitos recomendados 


| Cluster de nó único | 2 x 1GbE | 2 x 10GbE 


| Cluster de dois nós ou MetroCluster SDS | 4 x 1GbE ou 1 x 10GbE | 2 x 10GbE 


| Cluster de quatro, seis, oito, dez ou doze nós | 2 x 10GbE | 4 x 10GbE ou 2 x 25/40GbE 
|===


=== Requisitos de hardware adicionais baseados no tipo de instância

Existem vários requisitos adicionais de hardware com base no tipo de instância do nó.

link:concept_lic_platforms.html["Entenda as ofertas de licença da plataforma"]Consulte para obter mais informações.

[cols="a1,a2,a2,a2"]
|===
| Tamanho do nó | núcleos de CPU | Memória | Oferta de licença de plataforma necessária 


| Pequeno | Seis núcleos físicos ou mais, com quatro reservados para o ONTAP Select | 24 GB ou mais, com 16 GB reservados para ONTAP Select | Padrão, premium ou premium XL 


| Média | Dez núcleos físicos ou mais, com oito reservados para o ONTAP Select | 72 GB ou mais, com 64 GB reservados para ONTAP Select | Premium ou Premium XL 


| Grande | Dezoito núcleos físicos ou mais, com dezesseis reservados para o ONTAP Select | 136 GB ou mais, com 128 GB reservados para ONTAP Select | XL premium 
|===

NOTE: Existem requisitos de disco adicionais baseados na licença da plataforma. Consulte link:reference_plan_ots_storage.html["Armazenamento e RAID"] para obter mais informações.
