---
sidebar: sidebar 
permalink: reference_lic_ontap_features.html 
keywords: license, licensing, ontap features, default ontap features 
summary: O ONTAP Select oferece suporte completo para a maioria das funcionalidades do ONTAP. Muitos dos recursos do ONTAP são licenciados automaticamente para cada nó ao implantar um cluster. No entanto, alguns recursos exigem uma licença separada. 
---
= Suporte do ONTAP Select para recursos do ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O ONTAP Select suporta a maioria dos recursos do ONTAP . Muitos dos recursos do ONTAP são licenciados automaticamente para cada nó quando você implanta um cluster. No entanto, alguns recursos exigem uma licença separada.


NOTE: Os recursos do ONTAP que têm dependências específicas de hardware geralmente não são suportados com o ONTAP Select.



== Recursos do ONTAP licenciados por padrão

Os seguintes recursos do ONTAP são compatíveis com o ONTAP Select e licenciados por padrão:

* Proteção autônoma contra ransomware (ARP) (atualizações manuais)
* CIFS
* Deduplicação e compactação
* Gerenciamento externo de chaves usando o Protocolo de Interoperabilidade de Gerenciamento de Chaves (KMIP)
+
O gerenciamento de chaves externas é o único gerenciamento de chaves compatível com o ONTAP Select. Saiba mais link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-netapp-volume-encryption-concept.html["Habilitar e configurar o gerenciamento de chaves externas"^].

* FlexCache
+
ONTAP Select suporta FlexCache cache volumes com write-back. FlexCache origin volumes com write-back não são suportados.

+
link:concept_ots_overview.html#flexcache-write-back-with-ontap-select["Saiba mais sobre o recurso de write-back do FlexCache com ONTAP Select"]

* FlexClone
* ISCSI
* NDMP
* Encriptação de volume NetApp (apenas países não restritos)
* NFS
* NVMe sobre TCP
* Funcionalidade de alocação a vários clientes da ONTAP
* ONTAP S3
* S3 SnapMirror
* SnapLock Select
+
SnapLock Select é a implementação do ONTAP SnapLock projetada para ONTAP Select e inclui SnapLock Enterprise. Não inclui SnapLock Compliance.

+
link:https://docs.netapp.com/us-en/ontap/snaplock/index.html["Saiba mais sobre ONTAP SnapLock"^]

* SnapMirror
* SnapMirror cloud
* SnapRestore
* SnapVault
* Recuperação de desastres de VM de storage (SVM DR)
+
ONTAP Select suporta SVM DR como origem e destino, com um máximo de 16 relacionamentos. O suporte a SVM DR é limitado ao uso da versão do ONTAP até versões +2. Por exemplo, a origem ONTAP Select 9.16.1 pode se conectar a destinos ONTAP nas versões 9.16.1, 9.17.1 ou 9.18.1.





== Recursos do ONTAP licenciados separadamente

Você precisa adquirir uma licença separada para qualquer recurso do ONTAP que não esteja licenciado por padrão, incluindo:

* FabricPool
+

NOTE: Você não precisa de uma licença FabricPool ao utilizar o StorageGRID.

* MetroCluster SDS (oferta de licença premium ONTAP Select)


.Informações relacionadas
* link:concept_ots_overview.html#compare-ontap-select-and-ontap-9["Comparar ONTAP Select e ONTAP 9"]
* link:https://mysupport.netapp.com/site/systems/master-license-keys["Saiba mais sobre as chaves de licença mestra do NetApp ONTAP"^]

