---
sidebar: sidebar 
permalink: reference_api_workflow01.html 
keywords: rest api, deploy rest api, rest, workflow, create cluster, curl, json 
summary: Você pode implantar um cluster ONTAP Select de nó único em um host VMware ESXi gerenciado pelo vCenter. O cluster é criado com uma licença de avaliação. 
---
= Fluxo de trabalho 1: Crie um cluster de avaliação de nó único no ESXi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode implantar um cluster ONTAP Select de nó único em um host VMware ESXi gerenciado pelo vCenter. O cluster é criado com uma licença de avaliação.

O fluxo de trabalho de criação de cluster difere nas seguintes situações:

* O host ESXi não é gerenciado pelo vCenter (host autônomo)
* Vários nós ou hosts são usados dentro do cluster
* O cluster é implantado em um ambiente de produção com uma licença adquirida
* O hipervisor KVM é usado em vez do VMware ESXi
+
[NOTE]
====
** A partir do ONTAP Select 9.10.1, você não pode mais implantar um novo cluster no hipervisor KVM.
** A partir do ONTAP Select 9.11.1, toda a funcionalidade de gerenciamento não está mais disponível para clusters e hosts KVM existentes, exceto para as funções de remoção e exclusão offline.


====




== 1. Registre a credencial do vCenter Server

Ao implantar em um host ESXi gerenciado por um servidor vCenter, você deve adicionar uma credencial antes de Registrar o host. O utilitário de administração implantar pode usar a credencial para autenticar no vCenter.

[cols="15,15,70"]
|===
| Categoria | Verbo HTTP | Caminho 


| Implantar | POST | /security/credentials 
|===
Curl::


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step01 'https://10.21.191.150/api/security/credentials'
----
Entrada JSON (step01)::


[source, json]
----
{
  "hostname": "vcenter.company-demo.com",
  "type": "vcenter",
  "username": "misteradmin@vsphere.local",
  "password": "mypassword"
}
----
Tipo de processamento:: Assíncrono
Saída::
+
--
* ID de credencial no cabeçalho de resposta de localização
* Objeto trabalho


--




== 2. Registre um host de hipervisor

Você deve adicionar um host de hipervisor onde a máquina virtual que contém o nó ONTAP Select será executada.

[cols="15,15,70"]
|===
| Categoria | Verbo HTTP | Caminho 


| Cluster | POST | /hosts 
|===
Curl::


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step02 'https://10.21.191.150/api/hosts'
----
Entrada JSON (step02)::


[source, json]
----
{
  "hosts": [
    {
      "hypervisor_type": "ESX",
      "management_server": "vcenter.company-demo.com",
      "name": "esx1.company-demo.com"
    }
  ]
}
----
Tipo de processamento:: Assíncrono
Saída::
+
--
* ID do host no cabeçalho da resposta do local
* Objeto trabalho


--




== 3. Crie um cluster

Quando você cria um cluster ONTAP Select, a configuração básica do cluster é registrada e os nomes dos nós são gerados automaticamente pela implantação.

[cols="15,15,70"]
|===
| Categoria | Verbo HTTP | Caminho 


| Cluster | POST | /clusters 
|===
Curl:: O parâmetro de consulta node_count deve ser definido como 1 para um cluster de nó único.


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step03 'https://10.21.191.150/api/clusters? node_count=1'
----
Entrada JSON (step03)::


[source, json]
----
{
  "name": "my_cluster"
}
----
Tipo de processamento:: Síncrono
Saída::
+
--
* ID do cluster no cabeçalho de resposta do local


--




== 4. Configure o cluster

Existem vários atributos que você deve fornecer como parte da configuração do cluster.

[cols="15,15,70"]
|===
| Categoria | Verbo HTTP | Caminho 


| Cluster | PATCH | [cluster_id] 
|===
Curl:: Você deve fornecer o ID do cluster.


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step04 'https://10.21.191.150/api/clusters/CLUSTERID'
----
Entrada JSON (step04)::


[source, json]
----
{
  "dns_info": {
    "domains": ["lab1.company-demo.com"],
    "dns_ips": ["10.206.80.135", "10.206.80.136"]
    },
    "ontap_image_version": "9.5",
    "gateway": "10.206.80.1",
    "ip": "10.206.80.115",
    "netmask": "255.255.255.192",
    "ntp_servers": {"10.206.80.183"}
}
----
Tipo de processamento:: Síncrono
Saída:: Nenhum




== 5. Recupere o nome do nó

O utilitário de administração implantar gera automaticamente os identificadores e nomes dos nós quando um cluster é criado. Antes de poder configurar um nó, tem de recuperar a ID atribuída.

[cols="15,15,70"]
|===
| Categoria | Verbo HTTP | Caminho 


| Cluster | OBTER | /clusters/_cluster_id/nós 
|===
Curl:: Você deve fornecer o ID do cluster.


[source, curl]
----
curl -iX GET -u admin:<password> -k 'https://10.21.191.150/api/clusters/CLUSTERID/nodes?fields=id,name'
----
Tipo de processamento:: Síncrono
Saída::
+
--
* Array Registra cada um descrevendo um único nó com o ID e o nome exclusivos


--




== 6. Configure os nós

Você deve fornecer a configuração básica para o nó, que é a primeira de três chamadas de API usadas para configurar um nó.

[cols="15,15,70"]
|===
| Categoria | Verbo HTTP | Caminho 


| Cluster | CAMINHO | /clusters/cluster_id/node/node_id 
|===
Curl:: Você deve fornecer o ID do cluster e o ID do nó.


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step06 'https://10.21.191.150/api/clusters/CLUSTERID/nodes/NODEID'
----
Entrada JSON (step06):: Você deve fornecer a ID do host onde o nó ONTAP Select será executado.


[source, json]
----
{
  "host": {
    "id": "HOSTID"
    },
  "instance_type": "small",
  "ip": "10.206.80.101",
  "passthrough_disks": false
}
----
Tipo de processamento:: Síncrono
Saída:: Nenhum




== 7. Recupere as redes de nós

Você deve identificar os dados e as redes de gerenciamento usadas pelo nó no cluster de nó único. A rede interna não é usada com um cluster de nó único.

[cols="15,15,70"]
|===
| Categoria | Verbo HTTP | Caminho 


| Cluster | OBTER | /clusters/cluster_id/nodes/node_id/networks 
|===
Curl:: Você deve fornecer o ID do cluster e o ID do nó.


[source, curl]
----
curl -iX GET -u admin:<password> -k 'https://10.21.191.150/api/ clusters/CLUSTERID/nodes/NODEID/networks?fields=id,purpose'
----
Tipo de processamento:: Síncrono
Saída::
+
--
* Array de dois Registros cada um descrevendo uma única rede para o nó, incluindo a ID e a finalidade exclusivos


--




== 8. Configure a rede do nó

Você deve configurar os dados e as redes de gerenciamento. A rede interna não é usada com um cluster de nó único.


NOTE: Emita a seguinte chamada de API duas vezes, uma para cada rede.

[cols="15,15,70"]
|===
| Categoria | Verbo HTTP | Caminho 


| Cluster | PATCH | /clusters/cluster_id/node/node_id/networks/ network_id 
|===
Curl:: Você deve fornecer o ID do cluster, o ID do nó e o ID da rede.


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step08 'https://10.21.191.150/api/clusters/ CLUSTERID/nodes/NODEID/networks/NETWORKID'
----
Entrada JSON (step08):: Você precisa fornecer o nome da rede.


[source, json]
----
{
  "name": "sDOT_Network"
}
----
Tipo de processamento:: Síncrono
Saída:: Nenhum




== 9. Configure o pool de storage de nós

A etapa final na configuração de um nó é anexar um pool de storage. Você pode determinar os pools de storage disponíveis por meio do cliente da Web vSphere ou, opcionalmente, por meio da API REST de implantação.

[cols="15,15,70"]
|===
| Categoria | Verbo HTTP | Caminho 


| Cluster | PATCH | /clusters/cluster_id/node/node_id/networks/ network_id 
|===
Curl:: Você deve fornecer o ID do cluster, o ID do nó e o ID da rede.


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step09 'https://10.21.191.150/api/clusters/ CLUSTERID/nodes/NODEID'
----
Entrada JSON (step09):: A capacidade do pool é de 2 TB.


[source, json]
----
{
  "pool_array": [
    {
      "name": "sDOT-01",
      "capacity": 2147483648000
    }
  ]
}
----
Tipo de processamento:: Síncrono
Saída:: Nenhum




== 10. Implante o cluster

Depois que o cluster e o nó tiverem sido configurados, você poderá implantar o cluster.

[cols="15,15,70"]
|===
| Categoria | Verbo HTTP | Caminho 


| Cluster | POST | /clusters/cluster_id/deploy 
|===
Curl:: Você deve fornecer o ID do cluster.


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step10 'https://10.21.191.150/api/clusters/CLUSTERID/deploy'
----
Entrada JSON (step10):: Você deve fornecer a senha para a conta de administrador do ONTAP.


[source, json]
----
{
  "ontap_credentials": {
    "password": "mypassword"
  }
}
----
Tipo de processamento:: Assíncrono
Saída::
+
--
* Objeto trabalho


--

