---
sidebar: sidebar 
permalink: sizing-capacity-pool-license.html 
keywords: license, licensing, Capacity Tiers, usable, space 
summary: A licença Capacity Tiers baseia-se na capacidade de disco subjacente gerenciada por cada nó e não na capacidade utilizável do nó, par de HA ou cluster. Cada licença Capacity Tiers é atribuída a um número de série de nó individual para uma capacidade específica e requer um contrato de suporte correspondente. 
---
= Determine o tamanho da licença dos Capacity Pools para o ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A capacidade licenciada para uma licença de Capacity Pool é em quantidades inteiras de TB, com um mínimo de 2 TB. Você calcula a capacidade licenciada multiplicando a quantidade de espaço utilizável pelo fator de sobrecarga. O fator de sobrecarga estima a capacidade de sobrecarga do software ONTAP Select a ser retirada do espaço utilizável e se aplica à determinação da capacidade do ONTAP Select para unidades NVMe, SSD, HDD ou virtuais. O fator de sobrecarga difere entre clusters de nó único e clusters multinós (baseados em par de HA):

* O fator de sobrecarga para clusters de nó único é 1.13
* Fator de sobrecarga para clusters com vários nós é 2,67


Você precisa calcular a capacidade licenciada com base no espaço utilizável para garantir que você tenha o suficiente para sua implantação. Por exemplo, você quer 20 TB de capacidade utilizável para um par de HA (10 TB por nó):

* Com um par de HA, os dados são duplicados entre ambos os nós para redundância, então, para 20 TB de dados utilizáveis em um par de HA, você precisa ter 20 TB por nó, caso um dos nós fique offline.
* O fator 2,67 duplica a capacidade de cada nó e adiciona a capacidade de sobrecarga (0,67) necessária para o funcionamento do ONTAP Select.
* A capacidade de licença por nó é de 27 TB (10 x 2,67 = 26,7). Para o par de HA, você precisa de duas licenças de 27 TB para ter 20 TB de capacidade utilizável.


[cols="25,30,45"]
|===
| Descrição | Nó único | Par de HA ou combinação de par de HA e single-node 


| Capacidade utilizável | 20 TB | 10 TB por cluster de nó único 20 TB para par de HA 


| Espaço licenciado | 23 TB (20 x 1,13 = 22,6, arredondar para o próximo TB inteiro) | 54 TB (20 x 2,67 = 53,4, arredondar para o próximo TB inteiro) 


| Espaço máximo utilizável por nó *Nota*: O espaço máximo gerenciado por nó ou par de HA é 400 TB | 353 TB (400 / 1,13)  a| 
Por nó individual em um cluster:

149 TB (400 / 2,67)

Por par de HA em um cluster:

298 TB (2 x 149)

|===
.O que vem a seguir
link:task_lic_acquire_cp.html["Adquira uma licença Capacity Pools para ONTAP Select"]
