---
sidebar: sidebar 
permalink: sizing-capacity-tier-license.html 
keywords: license, licensing, Capacity Tiers, usable, space 
summary: A licença Capacity Tiers baseia-se na capacidade de disco subjacente gerenciada por cada nó e não na capacidade utilizável do nó, par de HA ou cluster. Cada licença Capacity Tiers é atribuída a um número de série de nó individual para uma capacidade específica e requer um contrato de suporte correspondente. 
---
= Considerações para o dimensionamento de uma licença ONTAP Select Capacity Tiers
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A licença Capacity Tiers baseia-se na capacidade de disco subjacente gerenciada por cada nó ONTAP Select e não na capacidade utilizável do nó, par de HA ou cluster. Cada licença Capacity Tiers é atribuída a um número de série de nó individual para uma capacidade específica e requer um contrato de suporte correspondente.

A capacidade licenciada para uma licença Capacity Tiers é em quantidades inteiras de TB, com um mínimo de 1 TB. Você calcula a capacidade licenciada multiplicando a quantidade de espaço utilizável pelo fator de sobrecarga. O fator de sobrecarga difere entre um cluster de nó único e clusters multinós (baseados em par de HA):

* O fator de sobrecarga para clusters de nó único é 1.13
* Fator de sobrecarga para clusters com vários nós é 2,67


Calcule a capacidade licenciada com base no espaço utilizável para garantir que você tenha o suficiente para sua implantação.

[cols="25,30,45"]
|===
| Descrição | Nó único | Par de HA 


| Capacidade utilizável | 10 TB | 5 TB por nó 10 TB para par de HA 


| Espaço licenciado | 12 TB (10 x 1,13 = 11,3, arredondar para o próximo TB inteiro) | Duas licenças de 14 TB (5 x 2,67 = 13,35, arredonde para o próximo TB inteiro) 


| Espaço máximo utilizável por nó *Nota*: O espaço máximo gerenciado por nó ou par de HA é 400 TB | 353 TB (400 / 1,13)  a| 
Por nó em um par de HA:

* 149 TB (400 / 2,67)


Por par de HA em um cluster com vários nós:

* Dois nós: 298 TB (2 x 149)
* Quatro nós: 596 TB (4 x 149)
* Seis nós: 894 TB (6 x 149)
* Oito nós: 1.192 TB (8 x 149)
* Dez nós: 1.490 TB (10 x 149)
* Doze nós: 1,788 TB (12 x 149)


|===
.O que vem a seguir
link:task_lic_acquire_ct.html["Adquira uma licença Capacity Tier para ONTAP Select"]
