---
sidebar: sidebar 
permalink: task_lic_acquire_cp.html 
keywords: license, licensing, acquire, Capacity Pools 
summary: Você precisa adquirir um arquivo de licença para cada pool de capacidade usado pelos nós do ONTAP Select. O arquivo de licença define a capacidade de armazenamento e a expiração do pool. Ele é bloqueado para o Gerenciador de licenças por meio de uma combinação do número de série de licença exclusivo atribuído pelo NetApp e o ID de bloqueio de licença associado à instância de implantação. 
---
= Adquirir uma licença do pool de capacidade do ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você precisa adquirir um arquivo de licença para cada pool de capacidade usado pelos nós do ONTAP Select. O arquivo de licença define a capacidade de armazenamento e a expiração do pool. Ele é bloqueado para o Gerenciador de licenças por meio de uma combinação do número de série de licença exclusivo atribuído pelo NetApp e o ID de bloqueio de licença associado à instância de implantação.

.Antes de começar
* Você deve ter o número de série da licença de nove dígitos atribuído ao Capacity Pool pela NetApp.
* Você deve aguardar pelo menos 24 horas após a data de envio do seu pedido de compra antes de adquirir o arquivo de licença.
* Você revisou o link:sizing-capacity-pool-license.html["Considerações para dimensionar uma licença de Capacity Pools"].


.Sobre esta tarefa
Você deve executar esta tarefa para cada pool de capacidade usado pelos nós do ONTAP Select.

.Passos
. Faça login no link:https://mysupport.netapp.com/site/["Site de suporte da NetApp"^].
. Selecione *Sistemas* > *Licenças de Software*.
. Digite o número de série da licença do Capacity Pool e selecione *Go!*
. Na página de detalhes da licença, navegue até a coluna *Detalhes do produto*.
. Selecione *Get NetApp License File* na linha apropriada.
. Digite o License Lock ID para sua instância do ONTAP Select Deploy e selecione *Enviar*.
. Selecione o método de entrega apropriado e selecione *Enviar*.
. Selecione *OK* na janela de confirmação de entrega.


.Depois de terminar
Você deve carregar o arquivo de licença no utilitário de administração Deploy antes que um nó do ONTAP Select possa usar o Pool de Capacidade.
