---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: Adicione uma imagem do ONTAP Select à sua instância do utilitário de administração Deploy. Após a instalação, você pode usá-la ao implantar um cluster ONTAP Select. 
---
= Adicione uma imagem ONTAP Select para implantar
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Adicione uma imagem do ONTAP Select à sua instância do utilitário de administração Deploy. Após a instalação da imagem, você pode usá-la ao implantar um cluster ONTAP Select.

.Antes de começar
Antes de adicionar novas imagens do ONTAP Select para implantar, você deve primeiro remover quaisquer imagens desnecessárias.


NOTE: Você só deve adicionar uma imagem ONTAP Select com uma versão anterior à versão original incluída na instância do utilitário de implantação. Adicionar versões posteriores do ONTAP Select à medida que elas se tornam disponíveis a partir do NetApp não é uma configuração suportada.



== Passo 1: Baixe a imagem de instalação.

Para iniciar o processo de adição de uma imagem ONTAP Select a uma instância do utilitário implantar, você deve baixar a imagem de instalação do site de suporte da NetApp. A imagem de instalação do ONTAP Select é formatada como um único arquivo compactado.

.Passos
. Acesse a link:https://mysupport.netapp.com/site/downloads/["Downloads do site de suporte da NetApp"^] página.
. Deslize para baixo e selecione *ONTAP Select Image*.
. Selecione a versão desejada da imagem de instalação.
. Reveja o Contrato de Licença de Utilizador final (EULA) e selecione *Accept & continue* (aceitar e continuar).
. Selecione e faça o download do pacote *ONTAP Select Image Install* apropriado. Responda a todas as solicitações conforme necessário.




== Etapa 2: Carregue a imagem de instalação para o Deploy.

Depois de adquirir a imagem de instalação do ONTAP Select, você deve fazer o upload do arquivo para a máquina virtual implantar.

.Antes de começar
Verifique se você tem o arquivo de imagem de instalação disponível em sua estação de trabalho local. Você também deve ter a senha da conta de usuário administrador do Deploy.

.Sobre esta tarefa
Esta tarefa descreve um método para carregar o arquivo na máquina virtual implantar. Pode haver outras opções mais adequadas para o seu ambiente.

.Passo
. Em um terminal de comandos em sua estação de trabalho local, carregue o arquivo de imagem para a máquina virtual de implantação, conforme mostrado nos exemplos a seguir:
+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


.Resultado
O arquivo de instalação do nó é armazenado no diretório inicial do usuário admin.



== Passo 3: Adicione a imagem de instalação

Adicione a imagem de instalação do ONTAP Select ao diretório de imagens de implantação para que ela esteja disponível ao implantar um novo cluster.

.Antes de começar
Você deve saber em qual diretório o arquivo de imagem de instalação foi colocado na máquina virtual do utilitário implantar. Supõe-se que o arquivo está no diretório home do administrador.

.Passos
. Inicie sessão na CLI do utilitário Deploy usando SSH com a conta de administrador (admin).
. Inicie o Bash shell:
+
[source, cli]
----
shell bash
----
. Coloque o arquivo de imagem de instalação no diretório de imagens, conforme mostrado no exemplo a seguir:
+
`tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`





== Passo 4: Exibir as imagens de instalação disponíveis

Exibir as imagens do ONTAP Select disponíveis ao implantar um novo cluster.

.Passos
. Acesse a página da Web da documentação on-line na máquina virtual do utilitário implantar e faça login usando a conta de administrador (admin):
+
`\http://<FQDN|IP_ADDRESS>/api/ui`

+
Use o nome de domínio ou o endereço IP da máquina virtual implantar.

. Navegue até a parte inferior da página e selecione *Implantar* e, em seguida, selecione *OBTER /imagens*.
. Selecione *Experimente!* para exibir as imagens disponíveis do ONTAP Select .
. Confirme se a imagem pretendida está disponível.

