---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: Você pode atualizar uma máquina virtual de utilitário de implantação existente no local usando a interface de linha de comando. 
---
= Atualizar uma instância do ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode atualizar uma máquina virtual de utilitário de implantação existente no local usando a interface de linha de comando.



== Antes de começar

Certifique-se de que o Deploy não é usado para executar outras tarefas durante a atualização. Você deve ver as notas da versão atual para obter informações e restrições sobre a atualização do utilitário de implantação.


NOTE: Se tiver uma instância mais antiga do utilitário de administração ONTAP Select Deploy instalada, deverá atualizar para a versão atual. O nó ONTAP Select e o componente ONTAP Select Deploy são atualizados independentemente. link:concept_adm_upgrading_nodes.html["Atualizar os nós de ONTAP Select"^]Consulte para obter mais detalhes.



== Baixe o pacote de atualização

Para iniciar o processo de atualização, você deve baixar o arquivo apropriado de atualização de máquina virtual de implantação do site de suporte da NetApp. O pacote de atualização é formatado como um único arquivo compactado.

.Passos
. Acesse o link:https://mysupport.netapp.com/site/["Site de suporte da NetApp"^] usando um navegador da Web e escolha *Downloads* no menu Downloads.
. Role para baixo e selecione *ONTAP Select Deploy Upgrade*.
. Selecione a versão desejada do pacote de atualização.
. Reveja o Contrato de Licença de Utilizador final (EULA) e selecione *Accept & continue* (aceitar e continuar).
. Selecione e baixe o pacote apropriado, respondendo a todas as solicitações conforme necessário para o seu ambiente.




== Faça o upload do pacote para a máquina virtual implantar

Depois de adquirir o pacote de atualização, você deve fazer o upload do arquivo para a máquina virtual implantar.

.Antes de começar
Tem de ter o ficheiro de atualização disponível na estação de trabalho local. Você também deve ter a senha para a conta de usuário do administrador.

.Sobre estas tarefas
Esta tarefa descreve um método para carregar o arquivo na máquina virtual implantar. Pode haver outras opções mais adequadas para o seu ambiente.

.Passos
. Em um shell de comando em sua estação de trabalho local, use o utilitário scp para carregar o arquivo de imagem para a máquina virtual implantar.
+
Exemplo

+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....


.Resultado
O arquivo de atualização é armazenado no diretório inicial do usuário admin.



== Aplique o pacote de atualização

Após o upload do arquivo de atualização para a máquina virtual implantar, você pode aplicar a atualização.

.Antes de começar
Você deve saber em qual diretório o arquivo de atualização foi colocado na máquina virtual do utilitário implantar. Além disso, certifique-se de que o Deploy não é usado para executar outras tarefas enquanto a atualização é realizada.

.Passos
. Inicie sessão na CLI do utilitário Deploy usando SSH com a conta de administrador.
. Execute a atualização usando o caminho do diretório e o nome do arquivo apropriados:
+
`deploy upgrade -package-path FILEPATH`

+
Exemplo

+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....


.Depois de terminar
Antes que o procedimento de atualização seja concluído, você será solicitado a criar um backup da configuração da máquina virtual de implantação. Além disso, você deve limpar o cache do navegador para que você possa visualizar as páginas de implantação recém-criadas.
