---
sidebar: sidebar 
permalink: task_cli_migrate_deploy.html 
keywords: administer, administering, cli, deploy, deploy instance, migrate 
summary: Você pode migrar uma instância existente do utilitário de administração implantar para uma nova máquina virtual usando a interface de linha de comando. 
---
= Migrar uma instância de implantação para uma nova máquina virtual
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode migrar uma instância existente do utilitário de administração implantar para uma nova máquina virtual usando a interface de linha de comando.

Este procedimento baseia-se na criação de uma nova máquina virtual que utilize os dados de configuração da máquina virtual original. As máquinas virtuais novas e originais devem executar a mesma versão e versão do utilitário de implantação. Não é possível migrar para uma versão e versão diferente do utilitário de implementação.



== Faça backup dos dados de configuração da implantação

Você deve criar um backup dos dados de configuração de implantação como parte da migração da máquina virtual. Você também deve criar um backup depois de implantar um cluster do ONTAP Select. Os dados são guardados num único ficheiro encriptado que pode transferir para a estação de trabalho local.

.Antes de começar
Certifique-se de que o Deploy não está executando nenhuma outra tarefa durante a operação de backup.

.Sobre esta tarefa
O arquivo de backup criado captura todos os dados de configuração da máquina virtual. Esses dados descrevem aspectos do seu ambiente de implantação, incluindo os clusters do ONTAP Select.

.Passos
. Inicie sessão na CLI do utilitário Deploy usando SSH com a conta de administrador.
. Crie um backup dos dados de configuração de implantação, que são armazenados em um diretório interno no servidor de implantação:
+
`deploy backup create`

. Forneça uma senha para o backup quando solicitado.
+
O ficheiro de cópia de segurança é encriptado com base na palavra-passe.

. Exibir os backups disponíveis no sistema:
+
`deploy backup show -detailed`

. Selecione seu arquivo de backup com base na data no campo *criado* e Registre o valor *URL de download*.
+
Você pode acessar o arquivo de backup através do URL.

. Usando um navegador da Web ou utilitário como o Curl, baixe o arquivo de backup para sua estação de trabalho local com o URL.




== Instale uma nova instância da máquina virtual implantar

Você deve criar uma nova instância da máquina virtual implantar que pode ser atualizada com os dados de configuração da máquina virtual original.

.Antes de começar
Você deve estar familiarizado com os procedimentos usados para baixar e implantar a máquina virtual ONTAP Select Deploy em um ambiente VMware.

.Sobre esta tarefa
Esta tarefa é descrita em um nível alto.

.Passos
. Crie uma nova instância da máquina virtual implantar:
+
.. Baixe a imagem da máquina virtual.
.. Implante a máquina virtual e configure a interface de rede.
.. Acesse o utilitário implantar usando SSH.




.Informações relacionadas
link:task_install_deploy.html["Instale o ONTAP Select Deploy"]



== Restaure os dados de configuração de implantação para a nova máquina virtual

Você deve restaurar os dados de configuração da máquina virtual do utilitário implantar original para a nova máquina virtual. Os dados estão em um único arquivo que você deve carregar de sua estação de trabalho local.

.Antes de começar
Tem de ter os dados de configuração de uma cópia de segurança anterior. Os dados estão contidos em um único arquivo e devem estar disponíveis em sua estação de trabalho local.

.Passos
. Em um shell de comando em sua estação de trabalho local, use o utilitário sftp para carregar o arquivo de backup na máquina virtual implantar.
+
Exemplo

+
....
sftp admin@10.234.81.101 (provide password when prompted)
put deploy_backup_20190601162151.tar.gz
exit
....
. Inicie sessão na CLI do utilitário Deploy usando SSH com a conta de administrador.
. Restaure os dados de configuração.
+
`deploy backup restore -path PATHNAME -filename FILENAME`

+
Exemplo

+
`deploy backup restore -path /home/admin -filename deploy_backup_20180601162151.tar.gz`


